import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ItemsProvider } from "./ItemsContext"; // Adjust the path as needed

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Pantry Tracker",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ItemsProvider>{children}</ItemsProvider>
      </body>
    </html>
  );
}
